version: "3.8"

services:
  backend:
    build: ./Backend
    container_name: backend
    image: backend
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    networks:
      - mern-net
    
  frontend:
    build: ./Frontend
    container_name: frontend
    image: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge