version: "3.8"

services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    networks:
      - mern-net
    
  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000
    networks:
      - mern-net

networks:
  mern-net:
    driver: bridge